### ISSUE TITLE
dotenvx.com vs dotenv.org? 

### ISSUE THREAD

**Issue by twardoch** [dotenv-org/dotenv-vault-python#26]
So there's https://dotenv.org/ (the TOS say Dotenv ("Company")) and https://dotenvx.com/ (the TOS say Dotenvx ("Company")). There are different Github orgs, different X accounts, different "companies" (but without any details). Both use the same logo and the same tagline "dotenv. better.". 

Neither project references the other. Are both legit? What's the relationship? Is one a scam? It all looks suspicious, perhaps unnecessarily. Some clarification would be useful. 

The projects that are about secret management are a bit too secretive themselves for my taste.

**Comment by motdotla** [comment]
answered here: https://github.com/orgs/dotenv-org/discussions/95#discussioncomment-9081746

hi @twardoch. yes, both are legit and both largely written by me - the creator of dotenv.

in terms of tech, dotenv.org (dotenv-vault) was created to solve the syncing of .env files. it's 100% a cloud product. you need the service to use it. but during it's development, I discovered we could provide 90% of the usefulness of it without needing the cloud - that was the invention of the `.env.vault` file.

we did a lot of work adjusting dotenv.org (dotenv-vault) around the `.env.vault` file, but foundationally we could never get quite there because of original design decisions a couple years back.

that's when we started building dotenvx. it works 100% without requiring a cloud product. it's a tool/lib (just like dotenv was).

i'm recommending dotenvx going forward, but dotenv-vault is currently more mature for large teams. we have plans to provide an easy migration path, but dotenvx's team features need at least 6 months more to mature before we do that.

apologies for this, but I'm a developer and not a business man so I tend to prioritize building a better tool - even if that confuses the business offering a bit. Eventually we'll solve this business offering confusion with the migration path I mentioned and by pulling dotenv.org into the dotenvx brand.

as to the legal naming, both are under the same California LLC and 'Dotenv' and 'Dotenvx' are DBAs.

also to add to this, we had a very well capitalized competitor swoop up the `dotenv.com` domain and sort of hold it captive as an attempt to acquire us. they are now graciously redirecting it for us, but we will likely never control it or be able to afford to purchase it off them. eventually, I settled on `dotenvx.com` as a good .com solution to this that also fit well with our goal of making a better dotenv. '10x', 'x-factor' - that sort of vibe. etc.

**Comment by twardoch** [comment]
Thanks for clarification. I was confused by the user-facing websites, since they might look by the surface as dome kinds of clones/imitations/competitors. (I can imagine others might be as well.)

The repos themselves give a somewhat clearer picture.
